

# Deployment Configuration
replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Service Account Configuration
serviceAccount:
  create: true
  automount: true
  annotations:
    description: "Service account for my-app"
  name: "my-app-sa"

resources: {}

# Service Configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Ingress Configuration
ingress:
  enabled: false
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "abdirahman.forum"
  hosts:
    - host: abdirahman.forum
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: abdirahman-forum-tls
      hosts:
        - abdirahman.forum
