controller:
  replicaCount: 2
  service:
    type: LoadBalancer
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  metrics:           # this turns on the prometheus metrics such as latency and request count
    enabled: true
    serviceMonitor:
      enabled: false

