name: EKS-Terraform Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - terraform/**

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1

jobs:
  terraform:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
     
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform plan
        uses: dflook/terraform-plan@v2
        with:
          path: .

      - name: Terraform apply
        uses: dflook/terraform-apply@v2
        with:
          path: .
          auto_approve: true