name: Delete Terraform Infrastructure 

on:
  workflow_dispatch:
    inputs:
      Terraform apply :
        description: "Terraform destroy "
        required: true
        type: string

  push:
    branches:
      - main
    paths:
      - terraform/**


permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: eks-assignment

jobs:
  apply:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      -  name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ env.AWS_REGION }}
      
      -  name: Terraform destroy
         uses: dflook/terraform-destroy@v2
         with:
          path: terraform